name: C# Continuous Integration

on:   
  push:
    branches: [ master, develop ]
    # if/when C++ implementation is added
    #paths-ignore:
      #- cpp/**
  pull_request:
    branches: [ master, develop ]
    # if/when C++ implementation is added
    #paths-ignore:
      #- cpp/**

jobs:
  build:
    runs-on: windows-latest
    env:
      working-directory: ./CSharp
      gibhub-ref: ${{ github.base_ref }}

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Branch name
      run: echo running on branch ${{github-ref}}
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
      working-directory: ${{env.working-directory}}
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ${{env.working-directory}}
    - name: Test
      run: dotnet test --no-restore --verbosity normal  
      working-directory: ${{env.working-directory}}
