name: C# Continuous Integration

on:   
  push:
    branches: [ main, develop ]
    # if/when C++ implementation is added
    paths-ignore:
      - cpp/**
      - .github/**
  pull_request:
    branches: [ main, develop ]
    # if/when C++ implementation is added
    paths-ignore:
      - cpp/**
      - .github/**
      - java/**
      - .gitignore

jobs:
  build:
    runs-on: windows-latest
    env:
      working-directory: ./CSharp

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Branch name
      run: echo running on branch ${GITHUB_REF}
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
      working-directory: ${{env.working-directory}}
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ${{env.working-directory}}
    - name: Test
      run: dotnet test --no-restore --verbosity normal  
      working-directory: ${{env.working-directory}}
