# This is a basic workflow to help you get started with Actions

name: Java Continuous Integration

on:   
  push:
    branches: [ main, develop ]
    paths-ignore:
      - cpp/**
      - .github/**
      - CSharp/**
      - .gitignore
  pull_request:
    branches: [ main, develop ]
    paths-ignore:
      - cpp/**
      - .github/**
      - CSharp/**
      - .gitignore

jobs:
  build-CredentialStore:
    runs-on: windows-latest
    env:
      working-directory: ./java/CredentialStore
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
          java-version: 1.11
    - name: Build with Maven
      run: mvn -B package
      # This step may duplicate efforts of package but is done to make the results of the test more clear
    - name: Test
      run: mvn -B test
